server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: weather
          destination: weather
          contentType: application/json
        event-out:
          destination: weather
          contentType: application/json
  datasource:
    url:  jdbc:h2:~/test
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    data: classpath:h2/data.sql
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: 8081
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: weather
          destination: weather
          contentType: application/json
        event-out:
          destination: weather
          contentType: application/json


